2018-01-19T19:25:13.966Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: Peer has rejected transaction '3e5c4ec57ea5e03884a073bea02b405b46505411ef62dc85e2083f8e1cd2e075' with code MVCC_READ_CONFLICT","stack":"Error: Error trying invoke business network. Error: Peer has rejected transaction '3e5c4ec57ea5e03884a073bea02b405b46505411ef62dc85e2083f8e1cd2e075' with code MVCC_READ_CONFLICT\n    at _initializeChannel.then.then.then.then.catch (/home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at process._tickCallback (internal/process/next_tick.js:109:7)"}$
2018-01-19T23:18:40.163Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org1$a89aea138fcdfe0b501f7904c25e3d22dc32d490' as the object already exists)
    at /home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-01-19T23:18:40.164Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org1$a89aea138fcdfe0b501f7904c25e3d22dc32d490' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org1$a89aea138fcdfe0b501f7904c25e3d22dc32d490' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)"}$
2018-01-19T23:44:55.054Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'd2dc2fc325a00355aef7e231bdf300a21dd8e253' in collection with ID 'Asset:org.acme.biznet.Tracks' does not exist)
    at /home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-01-19T23:44:55.055Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'd2dc2fc325a00355aef7e231bdf300a21dd8e253' in collection with ID 'Asset:org.acme.biznet.Tracks' does not exist)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'd2dc2fc325a00355aef7e231bdf300a21dd8e253' in collection with ID 'Asset:org.acme.biznet.Tracks' does not exist)\n\n    at _initializeChannel.then.then.then.then.catch (/home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)"}$
